// Code generated by protoc-gen-go.
// source: board.proto
// DO NOT EDIT!

/*
Package board is a generated protocol buffer package.

It is generated from these files:
	board.proto

It has these top-level messages:
	Ban
*/
package board

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Ban_Koma int32

const (
	// Fu
	Ban_F Ban_Koma = 1
	// Kyo
	Ban_K Ban_Koma = 2
	// Strawberry 1:5
	Ban_S Ban_Koma = 3
	// Color 1:6
	Ban_C Ban_Koma = 4
	// Empty
	Ban_E Ban_Koma = 101
)

var Ban_Koma_name = map[int32]string{
	1:   "F",
	2:   "K",
	3:   "S",
	4:   "C",
	101: "E",
}
var Ban_Koma_value = map[string]int32{
	"F": 1,
	"K": 2,
	"S": 3,
	"C": 4,
	"E": 101,
}

func (x Ban_Koma) Enum() *Ban_Koma {
	p := new(Ban_Koma)
	*p = x
	return p
}
func (x Ban_Koma) String() string {
	return proto.EnumName(Ban_Koma_name, int32(x))
}
func (x *Ban_Koma) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Ban_Koma_value, data, "Ban_Koma")
	if err != nil {
		return err
	}
	*x = Ban_Koma(value)
	return nil
}

type Ban struct {
	// Col[x][y] -> Koma
	Col              []*Ban_Col `protobuf:"bytes,1,rep,name=col" json:"col,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *Ban) Reset()         { *m = Ban{} }
func (m *Ban) String() string { return proto.CompactTextString(m) }
func (*Ban) ProtoMessage()    {}

func (m *Ban) GetCol() []*Ban_Col {
	if m != nil {
		return m.Col
	}
	return nil
}

type Ban_Col struct {
	Koma             []Ban_Koma `protobuf:"varint,1,rep,name=koma,enum=Ban_Koma" json:"koma,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *Ban_Col) Reset()         { *m = Ban_Col{} }
func (m *Ban_Col) String() string { return proto.CompactTextString(m) }
func (*Ban_Col) ProtoMessage()    {}

func (m *Ban_Col) GetKoma() []Ban_Koma {
	if m != nil {
		return m.Koma
	}
	return nil
}

func init() {
	proto.RegisterEnum("Ban_Koma", Ban_Koma_name, Ban_Koma_value)
}
